In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
import numpy as np
import keras
from keras import backend as K
from keras.layers.core import Dense
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing import image
from keras.models import Model
from keras.applications import imagenet_utils
from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt
%matplotlib inline

In [0]:
train_path = '/content/gdrive/My Drive/Colab Notebooks/Images/train' 
valid_path = '/content/gdrive/My Drive/Colab Notebooks/Images/valid'
test_path = '/content/gdrive/My Drive/Colab Notebooks/Images/test'

In [0]:
train_batches = ImageDataGenerator(preprocessing_function=keras.applications.mobilenet.preprocess_input).flow_from_directory(train_path, target_size=(224,224), batch_size=25)
valid_batches = ImageDataGenerator(preprocessing_function=keras.applications.mobilenet.preprocess_input).flow_from_directory(valid_path, target_size=(224,224), batch_size=25)
test_batches = ImageDataGenerator(preprocessing_function=keras.applications.mobilenet.preprocess_input).flow_from_directory(test_path, target_size=(224,224), batch_size=25, shuffle=False)

Found 1073 images belonging to 6 classes.
Found 138 images belonging to 6 classes.
Found 133 images belonging to 6 classes.


In [0]:
mobile = keras.applications.mobilenet.MobileNet()

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
17227776/17225924 [==============================] - 0s 0us/step


In [1]:
mobile.summary()

NameError: ignored

In [0]:
x = mobile.layers[-6].output
predictions = Dense(6, activation='softmax')(x)

In [0]:
model = Model(inputs=mobile.input, outputs=predictions)

In [0]:
model.summary()

In [0]:
for layer in model.layers[:-20]:
  layer.trainable = False

**Training**

In [0]:
model.compile(Adam(lr=.0001), loss='categorical_crossentropy', metrics=['accuracy'])

In [0]:
model.fit_generator(train_batches, steps_per_epoch=40, validation_data=valid_batches, validation_steps=6, epochs=60, verbose=2)

Instructions for updating:
Use tf.cast instead.
Epoch 1/60
 - 278s - loss: 0.5639 - acc: 0.8190 - val_loss: 1.7127 - val_acc: 0.1087
Epoch 2/60
 - 168s - loss: 0.1772 - acc: 0.9458 - val_loss: 1.7033 - val_acc: 0.1739
Epoch 3/60
 - 166s - loss: 0.1451 - acc: 0.9640 - val_loss: 1.5837 - val_acc: 0.1667
Epoch 4/60
 - 169s - loss: 0.1148 - acc: 0.9760 - val_loss: 1.3698 - val_acc: 0.2029
Epoch 5/60
 - 173s - loss: 0.1043 - acc: 0.9749 - val_loss: 1.1806 - val_acc: 0.2029
Epoch 6/60
 - 166s - loss: 0.0702 - acc: 0.9869 - val_loss: 1.2065 - val_acc: 0.2029
Epoch 7/60
 - 168s - loss: 0.0793 - acc: 0.9789 - val_loss: 1.2518 - val_acc: 0.2029
Epoch 8/60
 - 171s - loss: 0.0793 - acc: 0.9830 - val_loss: 1.0989 - val_acc: 0.9130
Epoch 9/60
 - 167s - loss: 0.0529 - acc: 0.9909 - val_loss: 1.0243 - val_acc: 0.9130
Epoch 10/60
 - 165s - loss: 0.0820 - acc: 0.9840 - val_loss: 1.0386 - val_acc: 0.9130
Epoch 11/60
 - 164s - loss: 0.0545 - acc: 0.9930 - val_loss: 1.0063 - val_acc: 0.8913
Epoch 12/60
 - 

In [0]:
model.save('/content/gdrive/My Drive/Colab Notebooks/fiodel.e.h5')

In [0]:
model.save('/content/gdrive/My Drive/Colab Notebooks/file_model.h5')

In [0]:
test_labels = test_batches.classes

In [0]:
predictions = model.predict_generator(test_batches, steps=6, verbose=0)

In [0]:
cm = confusion_matrix(test_labels, predictions.argmax(axis=1))

In [0]:
test_batches.class_indices

{'Blowhole': 0, 'Break': 1, 'Crack': 2, 'Fray': 3, 'Free': 4, 'Uneven': 5}

In [0]:
cm_plot_labels = ['0','1','2','3','4','5']
import pylab as pl

In [0]:
print(cm)

[[ 7  0  0  0  4  0]
 [ 1  1  2  1  1  2]
 [ 0  0  6  0  0  0]
 [ 0  0  0  0  2  1]
 [ 0  0  0  0 95  0]
 [ 0  0  0  0  4  6]]


In [0]:
from keras.models import load_model

Using TensorFlow backend.


In [0]:
new_model = load_model('/content/gdrive/My Drive/Colab Notebooks/file_model.h5')

W0614 05:43:56.238409 140639575967616 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0614 05:43:56.325757 140639575967616 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0614 05:43:56.377649 140639575967616 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:245: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0614 05:43:56.379076 140639575967616 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0614 05:43:56.380952 140639575

In [0]:
new_model.summary()

In [0]:
for layer in new_model.layers[:-20]:
  layer.trainable = False

In [0]:
new_model.fit_generator(train_batches, steps_per_epoch=40, validation_data=valid_batches, validation_steps=6, epochs=20, verbose=2)

Epoch 1/20
 - 273s - loss: 0.0267 - acc: 0.9970 - val_loss: 0.5570 - val_acc: 0.8986
Epoch 2/20
 - 139s - loss: 0.0217 - acc: 0.9960 - val_loss: 0.5055 - val_acc: 0.8913
Epoch 3/20
 - 142s - loss: 0.0273 - acc: 0.9960 - val_loss: 0.5828 - val_acc: 0.8768
Epoch 4/20
 - 143s - loss: 0.0291 - acc: 0.9960 - val_loss: 0.5196 - val_acc: 0.9058
Epoch 5/20
 - 144s - loss: 0.0268 - acc: 0.9970 - val_loss: 0.4974 - val_acc: 0.9130
Epoch 6/20
 - 147s - loss: 0.0252 - acc: 0.9970 - val_loss: 0.5120 - val_acc: 0.8986
Epoch 7/20
 - 147s - loss: 0.0136 - acc: 0.9980 - val_loss: 0.5282 - val_acc: 0.8696
Epoch 8/20
 - 147s - loss: 0.0271 - acc: 0.9940 - val_loss: 0.7309 - val_acc: 0.8768
Epoch 9/20
 - 147s - loss: 0.0353 - acc: 0.9940 - val_loss: 0.5190 - val_acc: 0.8768
Epoch 10/20
 - 143s - loss: 0.0202 - acc: 0.9960 - val_loss: 0.6377 - val_acc: 0.8841
Epoch 11/20
 - 145s - loss: 0.0217 - acc: 0.9960 - val_loss: 0.5702 - val_acc: 0.8696
Epoch 12/20
 - 143s - loss: 0.0254 - acc: 0.9960 - val_loss: 0.

In [0]:
new_model.save('/content/gdrive/My Drive/Colab Notebooks/file_new_model.h5')

In [0]:
test_labels = test_batches.classes

In [0]:
predictions = new_model.predict_generator(test_batches, steps=6, verbose=1)

6/6 [==============================] - 37s 6s/step


In [0]:
cm = confusion_matrix(test_labels, predictions.argmax(axis=1))

In [0]:
print(cm)

[[ 7  2  0  0  2  0]
 [ 1  3  1  1  1  1]
 [ 0  1  5  0  0  0]
 [ 0  0  0  0  2  1]
 [ 0  0  0  0 95  0]
 [ 0  0  0  0  1  9]]


In [0]:
new1_model = load_model('/content/gdrive/My Drive/Colab Notebooks/file_new_model.h5')

In [0]:
new1_model.summary()

In [0]:
for layer in new1_model.layers[:-20]:
  layer.trainable = False

In [0]:
new1_model.fit_generator(train_batches, steps_per_epoch=40, validation_data=valid_batches, validation_steps=6, epochs=15, verbose=2)

Epoch 1/15
 - 145s - loss: 0.0248 - acc: 0.9970 - val_loss: 0.5335 - val_acc: 0.8623
Epoch 2/15
 - 144s - loss: 0.0177 - acc: 0.9950 - val_loss: 0.5443 - val_acc: 0.8551
Epoch 3/15
 - 142s - loss: 0.0383 - acc: 0.9930 - val_loss: 0.5357 - val_acc: 0.9348
Epoch 4/15
 - 144s - loss: 0.0178 - acc: 0.9980 - val_loss: 0.6660 - val_acc: 0.8551
Epoch 5/15
 - 144s - loss: 0.0186 - acc: 0.9970 - val_loss: 0.6787 - val_acc: 0.8841
Epoch 6/15
 - 146s - loss: 0.0161 - acc: 0.9980 - val_loss: 0.6352 - val_acc: 0.8841
Epoch 7/15
 - 137s - loss: 0.0253 - acc: 0.9960 - val_loss: 0.6456 - val_acc: 0.8551
Epoch 8/15
 - 140s - loss: 0.0241 - acc: 0.9970 - val_loss: 0.7208 - val_acc: 0.9203
Epoch 9/15
 - 140s - loss: 0.0243 - acc: 0.9970 - val_loss: 0.7441 - val_acc: 0.8841
Epoch 10/15
 - 139s - loss: 0.0164 - acc: 0.9980 - val_loss: 0.5709 - val_acc: 0.8696
Epoch 11/15
 - 141s - loss: 0.0257 - acc: 0.9970 - val_loss: 0.5771 - val_acc: 0.8623
Epoch 12/15
 - 137s - loss: 0.0262 - acc: 0.9970 - val_loss: 0.

In [0]:
new1_model.save('/content/gdrive/My Drive/Colab Notebooks/file_new1_model.h5')

In [0]:
predictions = new1_model.predict_generator(test_batches, steps=6, verbose=2)

In [0]:
cm = confusion_matrix(test_labels, predictions.argmax(axis=1))

In [0]:
print(cm)

[[ 3  0  0  0  1  7]
 [ 4  0  3  0  1  0]
 [ 0  1  3  1  0  1]
 [ 0  1  2  0  0  0]
 [ 0  0  5  0 87  3]
 [ 0  0  0  0  8  2]]


In [0]:
new2_model = load_model('/content/gdrive/My Drive/Colab Notebooks/file_new1_model.h5')

In [0]:
new2_model.summary()

In [0]:
for layer in new2_model.layers[:-20]:
  layer.trainable = False

In [0]:
new2_model.fit_generator(train_batches, steps_per_epoch=40, validation_data=valid_batches, validation_steps=6, epochs=3, verbose=2)

Epoch 1/3
 - 139s - loss: 0.0222 - acc: 0.9970 - val_loss: 0.7140 - val_acc: 0.8768
Epoch 2/3
 - 136s - loss: 0.0248 - acc: 0.9960 - val_loss: 0.7538 - val_acc: 0.9058
Epoch 3/3
 - 134s - loss: 0.0240 - acc: 0.9970 - val_loss: 0.7479 - val_acc: 0.8986


In [0]:
new3_model = load_model('/content/gdrive/My Drive/Colab Notebooks/file_new_model.h5')

In [0]:
for layer in new3_model.layers[:-20]:
  layer.trainable = False

In [0]:
new3_model.fit_generator(train_batches, steps_per_epoch=40, validation_data=valid_batches, validation_steps=6, epochs=3, verbose=2)

Epoch 1/3
 - 140s - loss: 0.0290 - acc: 0.9950 - val_loss: 0.4558 - val_acc: 0.8841
Epoch 2/3
 - 137s - loss: 0.0164 - acc: 0.9980 - val_loss: 0.6339 - val_acc: 0.8768
Epoch 3/3
 - 135s - loss: 0.0290 - acc: 0.9940 - val_loss: 0.8232 - val_acc: 0.8406


In [0]:
predictions = new2_model.predict_generator(test_batches, steps=6, verbose=2)
cm = confusion_matrix(test_labels, predictions.argmax(axis=1))
print(cm)

In [0]:
predictions = new3_model.predict_generator(test_batches, steps=6, verbose=2)
cm = confusion_matrix(test_labels, predictions.argmax(axis=1))
print(cm)

[[ 0  0  0  0 11  0]
 [ 0  0  0  0  8  0]
 [ 0  0  0  0  6  0]
 [ 0  0  0  0  3  0]
 [17  0  7  1 66  4]
 [ 0  0  0  0 10  0]]


In [0]:
new4_model = load_model('/content/gdrive/My Drive/Colab Notebooks/file_model.h5')
for layer in new4_model.layers[:-20]:
  layer.trainable = False

In [0]:
new4_model.fit_generator(train_batches, steps_per_epoch=40, validation_data=valid_batches, validation_steps=6, epochs=4, verbose=2)

Epoch 1/4
 - 139s - loss: 0.0239 - acc: 0.9960 - val_loss: 0.4833 - val_acc: 0.9275
Epoch 2/4
 - 141s - loss: 0.0199 - acc: 0.9980 - val_loss: 0.5626 - val_acc: 0.8913
Epoch 3/4
 - 139s - loss: 0.0182 - acc: 0.9970 - val_loss: 0.6386 - val_acc: 0.8478
Epoch 4/4
 - 139s - loss: 0.0233 - acc: 0.9970 - val_loss: 0.5043 - val_acc: 0.8913


In [0]:
predictions1 = new4_model.predict_generator(test_batches, steps=6, verbose=2)
cm1= confusion_matrix(test_labels, predictions1.argmax(axis=1))
print(cm1)

[[ 0  0  0  0 10  1]
 [ 0  0  0  0  8  0]
 [ 0  0  0  0  6  0]
 [ 0  0  0  0  3  0]
 [ 7  0  3  1 77  7]
 [ 1  1  6  0  1  1]]


In [0]:
new5_model = load_model('/content/gdrive/My Drive/Colab Notebooks/file_new_model.h5')
for layer in new5_model.layers[:-20]:
  layer.trainable = False

In [0]:
new5_model.compile(Adam(lr=.00005), loss='categorical_crossentropy', metrics=['accuracy'])

In [0]:
new5_model.fit_generator(train_batches, steps_per_epoch=40, validation_data=valid_batches, validation_steps=6, epochs=4, verbose=2)

Epoch 1/4
 - 146s - loss: 0.0292 - acc: 0.9959 - val_loss: 0.5336 - val_acc: 0.9058
Epoch 2/4
 - 136s - loss: 0.0115 - acc: 0.9979 - val_loss: 0.5277 - val_acc: 0.9130
Epoch 3/4
 - 138s - loss: 0.0384 - acc: 0.9929 - val_loss: 1.0902 - val_acc: 0.2319
Epoch 4/4
 - 139s - loss: 0.0142 - acc: 0.9990 - val_loss: 0.6186 - val_acc: 0.8986


[[ 7  1  1  0  2  0]
 [ 1  3  1  1  1  1]
 [ 0  0  6  0  0  0]
 [ 0  0  0  1  2  0]
 [ 0  0  0  0 95  0]
 [ 0  0  0  0  2  8]]


In [0]:
new5_model.save('/content/gdrive/My Drive/Colab Notebooks/file_new5_model.h5')

In [0]:
new6_model = load_model('/content/gdrive/My Drive/Colab Notebooks/file_new5_model.h5')
for layer in new6_model.layers[:-20]:
  layer.trainable = False

In [0]:
new6_model.compile(Adam(lr=.000025), loss='categorical_crossentropy', metrics=['accuracy'])

In [0]:
new6_model.fit_generator(train_batches, steps_per_epoch=40, validation_data=valid_batches, validation_steps=6, epochs=2, verbose=2)

Epoch 1/2
 - 143s - loss: 0.0318 - acc: 0.9960 - val_loss: 0.6043 - val_acc: 0.9203
Epoch 2/2
 - 137s - loss: 0.0163 - acc: 0.9980 - val_loss: 0.6399 - val_acc: 0.8913


In [0]:
predictions4 = new6_model.predict_generator(test_batches, steps=6, verbose=2)
cm4= confusion_matrix(test_labels, predictions4.argmax(axis=1))
print(cm4)

[[ 0  0  0  0 11  0]
 [ 0  0  0  0  8  0]
 [ 0  0  0  0  4  2]
 [ 0  0  0  0  1  2]
 [ 8  4  7  1 68  7]
 [ 0  0  0  0 10  0]]


In [0]:
final_model = load_model('/content/gdrive/My Drive/Colab Notebooks/file_new5_model.h5')

In [0]:
predictions_final = final_model.predict_generator(test_batches, steps=6, verbose=2)
cm_final= confusion_matrix(test_labels, predictions_final.argmax(axis=1))
print(cm_final)

[[ 0  0  0  0 11  0]
 [ 0  0  0  0  8  0]
 [ 0  0  0  0  6  0]
 [ 0  0  0  0  3  0]
 [ 8  4  8  2 64  9]
 [ 0  0  0  0 10  0]]


In [0]:
new8_model = load_model('/content/gdrive/My Drive/Colab Notebooks/file_new_model.h5')
for layer in new8_model.layers[:-20]:
  layer.trainable = False

In [0]:
new8_model.compile(Adam(lr=.00005), loss='categorical_crossentropy', metrics=['accuracy'])

In [0]:
new8_model.fit_generator(train_batches, steps_per_epoch=40, validation_data=valid_batches, validation_steps=6, epochs=4, verbose=2)

Epoch 1/4
 - 146s - loss: 0.0185 - acc: 0.9980 - val_loss: 0.4908 - val_acc: 0.9420
Epoch 2/4


KeyboardInterrupt: ignored

In [0]:
predictions_f = new8_model.predict_generator(test_batches, steps=6, verbose=2)
cm_f= confusion_matrix(test_labels, predictions_f.argmax(axis=1))
print(cm_f)

[[ 0  0  0  0 11  0]
 [ 0  0  0  0  8  0]
 [ 0  0  0  0  6  0]
 [ 0  0  0  0  3  0]
 [ 8  2  9  1 64 11]
 [ 0  0  0  0 10  0]]


In [0]:
mobile1 = keras.applications.mobilenet.MobileNet()

W0614 10:39:52.773116 140639575967616 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


17227776/17225924 [==============================] - 0s 0us/step


In [0]:
y = mobile1.layers[-6].output
predictions = Dense(6, activation='softmax')(y)

In [0]:
modelf = Model(inputs=mobile1.input, outputs=predictions)

In [0]:
modelf.load_weights('/content/gdrive/My Drive/Colab Notebooks/file_new_model.h5')

In [0]:
predictions_f = modelf.predict_generator(test_batches, steps=6, verbose=2)
cm_f= confusion_matrix(test_labels, predictions_f.argmax(axis=1))
print(cm_f)

[[ 7  2  0  0  2  0]
 [ 1  3  1  1  1  1]
 [ 0  1  5  0  0  0]
 [ 0  0  0  0  2  1]
 [ 0  0  0  0 95  0]
 [ 0  0  0  0  1  9]]


In [0]:
for layer in modelf.layers[:-20]:
  layer.trainable = False

In [0]:
modelf.compile(Adam(lr=.00005), loss='categorical_crossentropy', metrics=['accuracy'])

In [0]:
modelf.fit_generator(train_batches, steps_per_epoch=40, validation_data=valid_batches, validation_steps=6, epochs=4, verbose=2)

Epoch 1/4
 - 144s - loss: 0.0253 - acc: 0.9970 - val_loss: 0.6337 - val_acc: 0.9058
Epoch 2/4
 - 134s - loss: 0.0230 - acc: 0.9970 - val_loss: 0.6253 - val_acc: 0.8986
Epoch 3/4
 - 134s - loss: 0.0241 - acc: 0.9960 - val_loss: 0.7638 - val_acc: 0.8768
Epoch 4/4
 - 135s - loss: 0.0216 - acc: 0.9970 - val_loss: 0.5837 - val_acc: 0.8986


In [0]:
predictions_f = modelf.predict_generator(test_batches, steps=6, verbose=2)
cm_f= confusion_matrix(test_labels, predictions_f.argmax(axis=1))
print(cm_f)

[[ 3  0  0  0  1  7]
 [ 4  0  2  0  2  0]
 [ 0  1  3  1  0  1]
 [ 0  1  2  0  0  0]
 [ 0  0  6  0 88  1]
 [ 0  0  0  0  8  2]]


In [0]:
modelf.load_weights('/content/gdrive/My Drive/Colab Notebooks/Final.h5')

In [0]:
for layer in modelf.layers[:-20]:
  layer.trainable = False

In [0]:
modelf.compile(Adam(lr=.000025), loss='categorical_crossentropy', metrics=['accuracy'])

In [0]:
modelf.fit_generator(train_batches, steps_per_epoch=40, validation_data=valid_batches, validation_steps=6, epochs=4, verbose=2)

Epoch 1/4
 - 150s - loss: 0.0283 - acc: 0.9970 - val_loss: 0.6878 - val_acc: 0.8696
Epoch 2/4
 - 136s - loss: 0.0202 - acc: 0.9960 - val_loss: 0.6443 - val_acc: 0.8768
Epoch 3/4
 - 137s - loss: 0.0215 - acc: 0.9970 - val_loss: 0.6269 - val_acc: 0.8986
Epoch 4/4
 - 137s - loss: 0.0203 - acc: 0.9970 - val_loss: 0.6066 - val_acc: 0.8913


In [0]:
predictions_f = modelf.predict_generator(test_batches, steps=6, verbose=2)
cm_f= confusion_matrix(test_labels, predictions_f.argmax(axis=1))
print(cm_f)

[[ 0  0  0  0 11  0]
 [ 0  0  0  0  8  0]
 [ 0  0  0  0  5  1]
 [ 0  0  0  0  2  1]
 [ 8  4  7  1 69  6]
 [ 0  0  0  0 10  0]]


In [0]:
modelf.load_weights('/content/gdrive/My Drive/Colab Notebooks/file_model.h5')

In [0]:
modelf.fit_generator(train_batches, steps_per_epoch=40, validation_data=valid_batches, validation_steps=6, epochs=4, verbose=2)

Epoch 1/4
 - 136s - loss: 0.0265 - acc: 0.9960 - val_loss: 0.6685 - val_acc: 0.8841
Epoch 2/4
 - 137s - loss: 0.0240 - acc: 0.9970 - val_loss: 0.7096 - val_acc: 0.9058
Epoch 3/4
 - 139s - loss: 0.0240 - acc: 0.9960 - val_loss: 0.6317 - val_acc: 0.8913
Epoch 4/4
 - 140s - loss: 0.0159 - acc: 0.9980 - val_loss: 0.5881 - val_acc: 0.8986


In [0]:
predictions_f = modelf.predict_generator(test_batches, steps=6, verbose=2)
cm_f= confusion_matrix(test_labels, predictions_f.argmax(axis=1))
print(cm_f)

[[ 0  0  0  0 11  0]
 [ 0  0  0  0  8  0]
 [ 0  0  0  0  6  0]
 [ 0  0  0  0  3  0]
 [ 8  0  8  1 66 12]
 [ 0  0  0  0 10  0]]
